import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  app: {
    width: '100%',
    height: '100vh',
    backgroundColor: '#1a1a1a',
    display: 'flex',
    flexDirection: 'column',
  },
  container: {
    flex: 1,
    display: 'flex',
    width: '100%',
    height: '100%',
    gap: '0',
  },
  controlPanel: {
    width: '280px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '20px',
    backgroundColor: '#0a0a0a',
    borderRight: '1px solid rgba(255, 255, 255, 0.1)',
    overflowY: 'auto',
  },
  avatarPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    backgroundColor: '#000',
  },
  avatarContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 600,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  buttonGroup: {
    display: 'flex',
    gap: '8px',
  },
  connectButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    padding: '16px',
    fontSize: '15px',
    fontWeight: 600,
    borderRadius: '8px',
    border: '2px solid rgba(255, 255, 255, 0.2)',
    backgroundColor: '#2a2a2a',
    color: 'rgba(255, 255, 255, 0.9)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  settingsButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    fontSize: '20px',
    borderRadius: '8px',
    border: '2px solid rgba(255, 255, 255, 0.2)',
    backgroundColor: '#2a2a2a',
    color: 'rgba(255, 255, 255, 0.9)',
    cursor: 'pointer',
    transition: 'all 0.2s',
    minWidth: '56px',
  },
  connectButtonActive: {
    borderColor: '#4ade80',
    backgroundColor: 'rgba(74, 222, 128, 0.1)',
  },
  connectButtonLoading: {
    cursor: 'wait',
    opacity: 0.7,
  },
  statusDotConnected: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#4ade80',
    animation: 'pulse 2s ease-in-out infinite',
  },
  statusDotDisconnected: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#ef4444',
  },
  spinner: {
    width: '16px',
    height: '16px',
    borderWidth: '2px',
  },
  errorBox: {
    display: 'flex',
    gap: '12px',
    padding: '16px',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '8px',
  },
  errorIcon: {
    fontSize: '20px',
  },
  errorContent: {
    flex: 1,
  },
  errorTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#fca5a5',
    marginBottom: '4px',
  },
  errorMessage: {
    fontSize: '13px',
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: '1.4',
  },
  infoBox: {
    padding: '12px',
    backgroundColor: 'rgba(100, 108, 255, 0.05)',
    border: '1px solid rgba(100, 108, 255, 0.2)',
    borderRadius: '6px',
  },
  infoTitle: {
    margin: '0 0 8px 0',
    fontSize: '13px',
    fontWeight: 600,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  infoList: {
    margin: 0,
    paddingLeft: '16px',
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: '11px',
    lineHeight: '1.5',
  },
  projectionHint: {
    padding: '8px',
    textAlign: 'center',
    fontSize: '11px',
    color: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: 'transparent',
    borderTop: '1px solid rgba(255, 255, 255, 0.05)',
  },
};
